<a href="https://colab.research.google.com/github/Vishhwassri32/indian-railway-delay-analysis/blob/main/indian_railway_delay_analys_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
import pandas as pd
uploaded = files.upload()

Saving indian_railway_delay_data_.csv to indian_railway_delay_data_.csv

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

In [3]:
df = pd.read_csv("indian_railway_delay_data_.csv")

In [4]:
df.head()

,Train_id,Train_name,Train_no,Source,Destitnation,Date,Distance(Km),Sc_arr__time,Act_arr_time,Dealy_min,Season,Run_frequency
0,E1,Begampura Express,12238,Varanasi,Jammu,01-01-2016 00:00,1260,06:30:00,07:45:00,01:15:00,Winter,Daliy
1,E2,Begampura Express,12238,Varanasi,Jammu,01-01-2017 00:00,1260,06:30:00,06:50:00,00:20:00,Winter,Daliy
2,E3,Begampura Express,12238,Varanasi,Jammu,01-01-2018 00:00,1260,06:30:00,08:00:00,01:30:00,Winter,Daliy
3,E4,Begampura Express,12238,Varanasi,Jammu,01-01-2019 00:00,1260,06:30:00,06:40:00,00:10:00,Winter,Daliy
4,E5,Begampura Express,12238,Varanasi,Jammu,01-01-2020 00:00,1260,06:30:00,07:00:00,00:30:00,Winter,Daliy

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Train_id       100 non-null    object
 1   Train_name     100 non-null    object
 2   Train_no       100 non-null    int64
 3   Source         100 non-null    object
 4   Destitnation   100 non-null    object
 5   Date           100 non-null    object
 6   Distance(Km)   100 non-null    int64
 7   Sc_arr__time   100 non-null    object
 8   Act_arr_time   100 non-null    object
 9   Dealy_min      100 non-null    object
 10  Season         100 non-null    object
 11  Run_frequency  100 non-null    object
dtypes: int64(2), object(10)
memory usage: 9.5+ KB

In [6]:
df.tail()

,Train_id,Train_name,Train_no,Source,Destitnation,Date,Distance(Km),Sc_arr__time,Act_arr_time,Dealy_min,Season,Run_frequency
95,D6,Vivek Express,15906,Dibrugarh,Kanyakumari,02-01-2021 00:00,4198,01-01-1900 19:25,19:25:00,00:00:00,Winter,Weekly
96,D7,Vivek Express,15906,Dibrugarh,Kanyakumari,03-01-2022 00:00,4198,01-01-1900 19:25,19:26:00,00:01:00,Winter,Weekly
97,D8,Vivek Express,15906,Dibrugarh,Kanyakumari,04-01-2023 00:00,4198,01-01-1900 19:25,19:34:00,00:09:00,Winter,Weekly
98,D9,Vivek Express,15906,Dibrugarh,Kanyakumari,01-01-2024 00:00,4198,01-01-1900 19:25,19:47:00,00:23:00,Winter,Weekly
99,D10,Vivek Express,15906,Dibrugarh,Kanyakumari,01-01-2025 00:00,4198,01-01-1900 19:25,19:56:00,00:31:00,Winter,Weekly

In [7]:
df.isna()

,Train_id,Train_name,Train_no,Source,Destitnation,Date,Distance(Km),Sc_arr__time,Act_arr_time,Dealy_min,Season,Run_frequency
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
x=df[['Sc_arr__time','Distance(Km)']]
y=df[['Dealy_min']]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42)

In [22]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [26]:
def clean_to_minutes(time_text):
    if pd.isna(time_text):
        return 0
    time_text = str(time_text).strip().split()[-1]
    try:
        h, m, s = map(int, time_text.split(':'))
        return h * 60 + m
    except:
        return 0

In [27]:
x= df['Distance(Km)'].tolist()
y = df['Delay_minutes'].tolist()

In [29]:
mean_x = sum(x) / len(x)
mean_y = sum(y) / len(y)

In [30]:
numerator = 0
denominator = 0
for i in range(len(x)):
    distance_diff = x[i] - mean_x
    delay_diff = y[i] - mean_y

    numerator += distance_diff * delay_diff
    denominator += distance_diff ** 2
m = numerator / denominator
c = mean_y - (m * mean_x)

print("--- MODEL TRAINING FINISHED ---")
print(f"Magic Slope (m): {m:.5f}")
print(f"Starting Point (c): {c:.2f}")

--- MODEL TRAINING FINISHED ---
Magic Slope (m): -0.00161
Starting Point (c): 38.73

In [31]:
new_train_distance = 1500
predicted_delay = (m * new_train_distance) + c
print("\n--- MAKING A NEW PREDICTION ---")
print(f"If a train travels {new_train_distance} km, our model guesses it will be late by: {predicted_delay:.2f} minutes!")

--- MAKING A NEW PREDICTION ---
If a train travels 1500 km, our model guesses it will be late by: 36.32 minutes!